"use client";

export default function Privacy() {
  return (
    <div className="container mx-auto px-4">
      <div className="bg-gray-1000 text-white py-100 py-12 px-2">
        <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>
        <div className="prose mx-5">	
          <p className="mb-7">Effective date: January 01, 2025</p>
          
          <p className="mb-4">Primuse Pte. Ltd. (“<strong>Primuse</strong>“, “we”, “us” or “our”) is committed to respecting your privacy. The purpose of this Privacy Policy (“<strong>Privacy Policy</strong>”) is to explain how we will use any personal information about you that we collect, use, share, and store of our websites – <a href="https://primusegroup.com">https://primusegroup.com</a>, <a href="https://primuse.net">https://primuse.net</a>, <a href="https://primuse.live">https://primuse.live</a>, <a href="https://kisum.com">https://kisum.com</a>, <a href="https://pclub.vip">https://pclub.vip</a>, <a href="https://fea.asia">https://fea.asia</a>, <a href="https://primuse.io">https://primuse.io</a>, <a href="https://primuse.world">https://primuse.world</a>, <a href="https://primuse.vip">https://primuse.vip</a> and <a href="https://primuse.org">https://primuse.org</a> ( the “<strong>Sites</strong>”), the disclosure of personal data when you use our services, the choices you have associated with that data and the rights you have in any personal data we hold about you. Also, to tell you about the policies and procedures that we have in place to respect your privacy and keep your personal data secure.</p>
          <p className="mb-4">This Policy applies to the Sites, applications, products and services (collectively, “Services”) on or in which it is posted, linked, or referenced.</p>
          <p className="mb-4">We use your data to provide and improve our services. By using our services, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from the Sites.</p>
          <p className="mb-4">This Privacy Policy applies to you if you:</p>
          <ul className="mb-4 list-disc ml-10">
              <li>Visit an <strong>Primuse</strong> facility, purchase a ticket for an event or at a venue owned, operated, promoted, or serviced by <strong>Primuse</strong>, its affiliates, subsidiaries and parent company;</li>
              <li>Use or access our products, services, or technology in venues and events we own or operate; and</li>
              <li>Interact with us online, use our mobile applications, visit our websites, or interact with or reference our products/services online, including via social media (e.g. when we correspond with you via social media, when we access information provided by social media platforms in relation to our pages on those platforms, or if you reference or interact with our Events and Venues (as defined below) on social media) (collectively, our &quot;Services&quot;).</li>
          </ul>
          
          <p className="mt-7"><strong>DEFINITIONS</strong></p>
          <ul className="mb-4 list-disc ml-10">
              <li><strong>Service:</strong> Service is all the online and offline applications operated by <strong>Primuse</strong> (such as websites, mobile applications, venues, etc..) and all the services offered by <strong>Primuse</strong> (more info at <a href="https://www.primusegroup.com/divisions/">https://www.primusegroup.com/divisions/</a></li>
              <li><strong>Personal Data:</strong> Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
              <li><strong>Usage Data:</strong> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
              <li><strong>Cookies:</strong> Cookies are small files stored on your device (computer or mobile device).</li>
          </ul>
          
          <p className="mt-7"><strong>INFORMATION COLLECTION AND USE</strong></p>
          <p className="mb-4">We collect several different types of information for various purposes to provide and improve our Services to you.</p>
          <p className="mb-4">Types of Data Collected:</p>

          <div className="prose mx-5">
            <p className="mt-7"><strong>I.- Personal Data</strong></p>
            <p className="mb-4">While using our Services, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include, but is not limited to:</p>
            <ul className="mb-4 list-disc ml-10">
                <li>Identity information, such as your first name, last name, username or similar identifier, title, date of birth and gender;</li>
                <li>Contact information, such as your email address and telephone number;</li>
                <li>Profile information, such as your username and password, interests, preferences, feedback and survey responses;</li>
                <li>Feedback and correspondence, such as information you provide in your responses to surveys, when you participate in market research activities, report a problem with Service, receive customer support or otherwise correspond with us;</li>
                <li>Financial information, such as your credit card or other payment card details;</li>
                <li>Transaction information, such details about purchases you make through the Service and billing details;</li>
                <li>Usage information, such as information about how you use the Service and interact with us;</li>
                <li>Marketing information, such as your preferences for receiving marketing communications and details about how you engage with them;</li>
                <li>Financial information, such as bank account number and bank routing number; financial assets holdings; and</li>
                <li>Technical information, such as your Ethereum wallet address and network information regarding transactions. Please note that your Ethereum wallet address is not collected by https://primuse.io/ or associated plugins and mobile applications (“Primuse Club App”).</li>
                <li>Cookies and Usage Data</li>
            </ul>          
            
            
            <p className="mt-7"><strong>II.- Further Information We Collect In Relation to the P•Club, Primuse Club and Primuse Club Services.&nbsp;</strong></p>
            <p className="mb-4">Further information we collect from you in relation to <a href="https://primuse.vip/">https://primuse.vip/</a> and <a href="https://pclub.vip">https://pclub.vip</a> (the “Primuse Club Site”) and Primuse Club Services may include:</p>
            <ul className="mb-4 list-disc ml-10">
              <li>Further identity information, such as your country of birth, nationality, national ID number, place of birth, employer and occupation;</li>
              <li>Passport and/or photo ID for identity verification purposes;&nbsp;</li>
              <li>Information required to comply with anti-money laundering (AML) laws and know-your-customer (KYC) requirements (such as nationality and place of birth);&nbsp;</li>
              <li>Source of funds for participating in token launches; and</li>
              <li>Information that you give us in relation to your purchased token holdings, such as earnings received from staking, and the number of tokens in your wallet.&nbsp;</li>
            </ul>
            
            <p className="mt-7"><strong>III.- Usage Data</strong></p>
            <p className="mb-4">We may also collect information on how the Services is accessed and used (&quot;Usage Data&quot;). This Usage Data may include information such as your computer&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
            <p className="mb-4">We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.</p>
            
            <p className="mt-7"><strong>IV.- Tracking &amp; Cookies Data</strong></p>
            <p className="mb-4">We use cookies and similar tracking technologies to track the activity on our Services and we hold certain information.</p>
            <p className="mb-4">Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Other tracking technologies are also used such as beacons, tags and scripts to collect and track information and to improve and analyse our Services.</p>
            <p className="mb-4">You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Services.</p>
            
            <p className="mb-4">Examples of Cookies we use:</p>
            <ul className="mb-4 list-disc ml-10">
              <li>Session Cookies. We use Session Cookies to operate our Service.</li>
              <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
              <li>Security Cookies. We use Security Cookies for security purposes.</li>
            </ul>
          </div>
          
          <p className="mb-4">More info about our Cookies Policy: <a href="https://www.primusegroup.com/cookies-policy/">https://www.primusegroup.com/cookies-policy/</a></p>
          
          <p className="mt-7"><strong>USE OF DATA</strong></p>
          <p className="mb-b"><strong>Primuse</strong> uses the collected data for various purposes:</p>
          
          <ul className="mb-4 list-disc ml-10">
            <li>To provide and maintain our Services</li>
            <li>To notify you about changes to our Services</li>
            <li>To allow you to participate in interactive features of our Services when you choose to do so</li>
            <li>To provide customer support</li>
            <li>To gather analysis or valuable information so that we can improve our Service</li>
            <li>To monitor the usage of our Services</li>
            <li>To detect, prevent and address technical issues</li>
            <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
            <li>To comply with law, as we believe necessary or appropriate to comply with applicable laws (including anti-money laundering (AML) laws and know-your-customer (KYC) requirements), lawful requests and legal process, such as to respond to subpoenas or requests from government authorities.</li>
            <li>For compliance, fraud prevention, and safety; to protect, investigate, and deter against fraudulent, unauthorized, or illegal activity.</li>
          </ul>
          
          <p className="mt-7"><strong>TRANSFER OF DATA</strong></p>
          <p className="mb-4">The Company has offices outside of the EU and has affiliates and service providers in Singapore and in other countries. Your personal information, including Personal Data, may be transferred — and maintained on — computers to or from Singapore or other locations outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction. Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>
          <p className="mb-4">EU users should read the important information provided&nbsp; below about transfer of personal information outside of the European Economic Area (EEA).</p>
          <p className="mt-4"><strong>Primuse</strong> will take all the steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of your data and other personal information.</p>
          
          <p className="mt-7"><strong>DISCLOSURE OF DATA</strong></p>
          <div className="prose mx-5">
            <p className="mt-4"><strong>I.- Disclosure for Law Enforcement</strong></p>
            <p>Under certain circumstances, Primuse may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            
            <p className="mt-4"><strong>II.- Legal Requirements</strong></p>
            <p>Primuse may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
            <ul className="mt-4 list-disc ml-10">
              <li>To comply with a legal obligation</li>
              <li>To protect and defend the rights or property of Primuse</li>
              <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>To protect the personal safety of users of the Service or the public</li>
              <li>To protect against legal liability</li>
            </ul>
          </div>
          
          <p className="mt-7"><strong>SECURITY OF DATA</strong></p>
          <p className="mb-4">The security of your data is important to us but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
          
          <p className="mt-7"><strong>SERVICE PROVIDERS</strong></p>
          <p className="mb-4">We may employ third party companies and individuals to facilitate our Services (“Service Providers”), provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>
          <p className="mb-4">These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>
          <div className="prose mx-5">
            <p className="mt-7"><strong>I.- Payments</strong></p>
            <p className="mb-4">We may provide paid products and/or services within the Services. In that case, we use third-party services for payment processing (e.g. payment processors).</p>
            <p className="mb-4">We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, MasterCard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>
          </div>

          <p className="mt-7"><strong>LINKS TO OTHER SITES</strong></p>
          <p className="mb-4">Our Services may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that third party&apos;s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
          <p className="mb-4">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          
          <p className="mt-7"><strong>CHILDREN&apos;S PRIVACY</strong></p>
          <p className="mb-4">Our Service does not address anyone under the age of 18 (&quot;Children&quot;).</p>
          <p className="mb-4">We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>
          
          <p className="mt-7"><strong>CHANGES TO THIS PRIVACY POLICY</strong></p>
          <p className="mb-4">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
          <p className="mb-4">We will let you know via email and/or a prominent notice on our Service, prior to the change becoming effective and update the “effective date” at the top of this Privacy Policy.</p>
          <p className="mb-4">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          
          <p className="mt-7"><strong>NOTICE TO EU DATA SUBJECTS</strong></p>

          <div className="prose mx-5 mb-4">
            <p className="mt-4"><strong>I.- Personal Information</strong></p>
            <p className="mb-4">With respect to EU data subjects, “personal information,” as used in this Privacy Policy, is equivalent to “personal data” as defined in the&nbsp;<a href="https://gdpr-info.eu/art-4-gdpr/">European Union General Data Protection Regulation</a> (https://gdpr-info.eu/art-4-gdpr/) (GDPR).&nbsp;</p>
            
            <p className="mt-4"><strong>II.- Legal Bases for Processing</strong></p>
            <p className="mb-4">We only use your personal information as permitted by law. We are required to inform you of the legal bases of our processing of your personal information, which are described in the table below. If you have questions about the legal bases under which we process your personal information, contact us at&nbsp;privacy@primuse.net.</p>
            
            <p className="mt-4"><strong>III.- Processing Purpose &amp; Legal Basis:</strong></p>
            <div className="prose mx-5 mb-4">
              <p className="mb-3">a) <em><u>To provide our service:</u></em> <em>Our processing of your personal information is necessary to perform the contract governing our provision of the Services or to take steps that you request prior to signing up for the Service.</em></p>
              <p className="mb-3">b) <em><u>To communicate with you; To optimize our platform; For compliance, fraud prevention, and safety; To provide our service:</u></em> <em>These processing activities constitute our legitimate interests. We make sure we consider and balance any potential impacts on you (both positive and negative) and your rights before we process your personal information for our legitimate interests. We do not use your personal information for activities where our interests are overridden by any adverse impact on you (unless we have your consent or are otherwise required or permitted to by law).</em></p>
              <p className="mb-3">c) <em><u>To comply with law:</u></em> <em>We use your personal information to comply with applicable laws and our legal obligations, including anti-money laundering (AML) laws and know-your-customer (KYC) requirements.</em></p>
              <p className="mb-3">d) <em><u>With your consent:</u></em> <em>Where our use of your personal information is based upon your consent, you have the right to withdraw it anytime in the manner indicated in the Service or by contacting us at&nbsp;<u>privacy@primuse.net</u>.</em></p>
            </div>

            <p className="mt-4"><strong>IV.- Sensitive Data</strong></p>
            <p className="mb-4">Some of the information you provide us may constitute sensitive data as defined in the GDPR (also referred to as special categories of personal data), including identification of your race or ethnicity on government-issued identification documents.</p>
            
            <p className="mt-4"><strong>V.- Use for New Purposes</strong></p>
            <p className="mb-4">We may use your personal information for reasons not described in this Privacy Policy, where we are permitted by law to do so and where the reason is compatible with the purpose for which we collected it. If we need to use your personal information for an unrelated purpose, we will notify you and explain the applicable legal basis for that use. If we have relied upon your consent for a particular use of your personal information, we will seek your consent for any unrelated purpose.</p>
            
            <p className="mt-4"><strong>VI.- Your Rights</strong></p>
            <p className="mb-4">Under the GDPR, you have certain rights regarding your personal information. You may ask us to take the following actions in relation to your personal information that we hold:</p>
            <div className="prose mx-5 mb-4">
              <ul className="mb-4 list-disc ml-10">
                <li>Stop sending you direct marketing communications which you have previously consented to receive. We may continue to send you Service-related and other non-marketing communications.</li>
                <li>Provide you with information about our processing of your personal information and give you access to your personal information.</li>
                <li>Update or correct inaccuracies in your personal information.</li>
                <li>Delete your personal information.</li>
                <li>Transfer a machine-readable copy of your personal information to you or a third party of your choice.</li>
                <li>Restrict the processing of your personal information.</li>
                <li>Object to our reliance on our legitimate interests as the basis of our processing of your personal information that impacts your rights.</li>
              </ul>
            </div>
            <p className="mb-4">You can submit these requests by email to&nbsp;privacy@primuse.net. We may request specific information from you to help us confirm your identity and process your request. Applicable law may require or permit us to decline your request. If we decline your request, we will tell you why, subject to legal restrictions. If you would like to submit a complaint about our use of your personal information or response to your requests regarding your personal information, you may contact us at&nbsp;privacy@primuse.net or submit a complaint to the data protection regulator in your jurisdiction. You can find your data protection regulator&nbsp;<a href="https://ec.europa.eu/justice/article-29/structure/data-protection-authorities/index_en.htm">here</a> (https://ec.europa.eu/justice/article-29/structure/data-protection-authorities/index_en.htm).</p>
            
            <p className="mt-4"><strong>VII.- Cross-Border Data Transfer</strong></p>
            <p className="mb-4">Please be aware that your personal data will be transferred to, processed, and stored in Singapore. Data protection laws in Singapore may be different from those in your country of residence. You consent to the transfer of your information, including personal information, to Singapore as set forth in this Privacy Policy by visiting our Sites or using our service.</p>
            <p className="mb-4">Whenever we transfer your personal information out of the EEA to Singapore or countries not deemed by the European Commission to provide an adequate level of personal information protection, the transfer will be based on a data transfer mechanism recognized by the European Commission as providing adequate protection for personal information.</p>
            
          </div>
          <p className="mb-4 mt-7">Please contact us if you want further information on the specific mechanism used by us when transferring your personal information out of the EEA.</p>
          
          <p className="mt-10"><strong>CONTACT US</strong></p>
          <p className="mb-4 mt-4">If you have any questions about this Privacy Policy, please contact us:</p>
          <p className="mb-4">Primuse Pte. Ltd.<br />E-Mail: info@primuse.net</p>
          <p className="mb-4">This document was last updated on January 01, 2025</p>
        </div>
      </div>
    </div>
  );
}